-- Criação da tabela para dispositivos Sonoff
CREATE TABLE IF NOT EXISTS sonoff (
  id BIGINT NOT NULL AUTO_INCREMENT,
  nome VARCHAR(255) NOT NULL,
  ip VARCHAR(100) NOT NULL,
  maquina VARCHAR(255) NOT NULL,
  dt_create DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  dt_update DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  dt_delete DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_sonoff_ip (ip)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;